pressly/sup

cmd/sup/main.go
sup.go
supfile.go
tar.go
task.go

* SUP_NETWORK contains the name of the current network in use
* SUP_HOST contains the address of the current host in use

Added default environment variables SUP_NETWORK and SUP_HOST

---

cmd/sup/main.go
sup.go
supfile.go
tar.go
task.go

Exclude option can be used like:
```
upload:
desc: Upload this repository
upload:
- src: ./
dst: /tmp/$IMAGE
exclude: node_modules, src, scripts
```

Exclude option

---

ssh.go
sup.go
supfile.go

A lot of setups tunnel through a jump host (bastion host), this adds support for tunnelling in `sup`.

Add SSH proxy support

---

sup.go
task.go

Fix "Bad file descriptor on localhost"

---

cmd/sup/main.go
example/Supfile
supfile.go

Comments more than welcome.
Addresses #9

Add inventory to Network allowing for re-use and dynamic lookup

---

cmd/sup/main.go
supfile.go

Make inventory a single command, parse it just once

---

README.md
cmd/sup/main.go

Run multiple targets/commands

---

cmd/sup/main.go

Fix $SUP_USER on cross-compiled binaries

---

Glockfile
sup.go

Update import path of prefixer

---

supfile.go

currently SUP_TIME override is not working due to this bug

fix EnvList.Set override

---

README.md
cmd/sup/main.go

Implement passing env vars via CLI --env flag

---

client.go
localhost.go
ssh.go
sup.go

- Works on localhost.
- ~~Doesn't work on SSH yet. Seems like the SSH session doesn't
send signals correctly, unless we have working pseudo-TTY.~~
- SSH works now!
Fixes #2

Delegate ^C Interrupt signal

---

README.md
cmd/sup/main.go
localhost.go
ssh.go
sup.go
task.go

CLI: Implement --debug and --disable-prefix options

---

index.html

@VojtechVitek let me know when we hit the next order of magnitude (10000) as I'll have to update it again.

Fix iframe width to show larger star count!

---

tar.go

Fix uploading issue when `src` is an absolute path

---

supfile.go

I fixed an error message for unsupported Supfile version for avoiding confused experience

[Resolve #116] Fix an error message for unsupported Supfile version

---

.travis.yml
ssh.go

Related: #86
Builds on top of #121

SSH ~/.ssh/id_* private key wildcard

---

cmd/sup/main.go
supfile.go

Follow-up for #105

---

cmd/sup/main.go

Support Supfile.yml

---

cmd/sup/main.go
supfile.go

Resolves https://github.com/pressly/sup/issues/127

Run network's inventory only when actually used

---

README.md
index.html

Solves https://github.com/pressly/sup/issues/102

Update docs about running a Supfile from a Supfile
